---

s3-scality:
  image: rackattack-nas.dc1:5000/staging/s3-scality:latest
  container_name: s3-scality.service.strato
  dns_search: service.strato
  volumes:
    - /var/log/stratoscale:/var/log/stratoscale:rw,Z
    - /etc/stratoscale/:/etc/stratoscale/:ro
    - /etc/localtime:/etc/localtime:ro
    - /usr/bin/consul:/usr/bin/consul:rw,Z
    - /mnt/s3:/s3/:rw,Z
  environment:
    S3DATAPATH: "/s3/data"
    S3METADATAPATH: "/s3/meta"
    VERIFY_SERVICE_ENABLED: True
  net: "host"
